# Root directory for all artifacts
artifacts_root: artifacts

# Configuration related to data ingestion
data_ingestion:

  # Directory where data ingestion artifacts are stored
  root_dir: artifacts/data_ingestion

  # Path to the local file where the data is already saved
  local_data_file: /Users/macbookpro/Documents/semantic_preprocessor_model/semantic_preprocessor_model/data/data.csv


  # Configuration related to data validation
data_validation:
  # Directory where data validation results and artifacts are stored
  root_dir: artifacts/data_validation
  
  # Path to the ingested data file that will be used for validation
  data_source_file: artifacts/data_ingestion/data.csv
  
  # Path to the file that captures the validation status (e.g., success, errors encountered)
  status_file: artifacts/data_validation/status.txt


# Configuration related to data transformation
data_transformation:
  # Directory where data transformation results and artifacts are stored
  root_dir: artifacts/data_transformation
  
  # Path to the ingested data file that will be used for validation
  data_source_file: artifacts/data_ingestion/data.csv

  # Path to data validation status
  data_validation: artifacts/data_validation/status.txt


# Configuration related to model training
model_training:
  # Directory where model training results and artifacts are stored
  root_dir: artifacts/model_trainer
  
  # Path to the train features
  train_features_path: artifacts/data_transformation/train_features.npz
  
  # Path to the validation features
  val_features_path: artifacts/data_transformation/val_features.npz
  
  # Path to train labels
  train_labels_path: artifacts/data_transformation/train_labels.csv
  
  # Path to validation labels
  val_labels_path: artifacts/data_transformation/val_labels.csv
  
  # Path to save the trained model
  model_name: model.joblib



# Configuration for Model Evaluation

model_evaluation:
  # Root directory for saving model evaluation artifacts
  root_dir: artifacts/model_evaluation
  
  # Path to the val data used for evaluation
  val_features_path: artifacts/data_transformation/val_features.npz
  val_labels_path: artifacts/data_transformation/val_labels.csv
  
  # Path to the trained model saved during the training step
  model_path: artifacts/model_trainer/model.joblib
  
  # Path to save the evaluation metrics in JSON format
  metric_file_path: artifacts/model_evaluation/metrics.json

  # MLFlow URI
  mlflow_uri: 'https://dagshub.com/etietopabraham/semantic_preprocessor_model.mlflow'
